### ISSUE TITLE
Sequential access

### ISSUE THREAD

**Issue by dragosperca** [serbanrobu/dbd#1]
Creating concurrent database backups (multiple backups made by different users in the same time) can trigger a sustained load on the server, sometimes causing database locks / issues with zombie mysqldump/pg_dump processes.
An idea is to have a lock file on the dbd_agent, which will only allow a single request to be made at a time.

Scenario:
- USER1 starts a DB clone. dbd_agent will create a lock file encoding which user started the process and when
- USER2 wants to start a clone. dbd_agent will check the existence of this lock file and will refuse the request with a message: "USER1 is currently running a backup, process started at TIMESTAMP"

Not everybody will want to enforce sequential access, so this should be configurable within the toml file of the agent.

I'm writing the idea here, hopefully I'll follow it up with a PR.

**Comment by serbanrobu** [comment]
The 0.3.1 release should fix this.
